# Generated by Django 4.1.1 on 2022-11-11 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_rename_user_userprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='User',
        ),
    ]
