# Generated by Django 4.1.1 on 2022-11-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publish_data',
            new_name='publish_date',
        ),
    ]
